### ISSUE TITLE
Error generating report outputs. float division by zero

### ISSUE THREAD

**Issue by PeerHerholz** [neuroscout/neuroscout#769] opened 2020-05-29 01:24 UTC
Ahoi hoi folks,

I was starting to check/evaluate `AudioSet auditory labels`, beginning with the `Study Forrest` dataset. I selected the most distinct labels along with some classic noise regressors as you can see [here](https://neuroscout.org/builder/AYyYj). While it compiled successfully, I receive an error saying `Error generating report outputs. float division by zero`. Before I run the analysis and/or try to dig deeper: has anyone an idea of what might be going on here? 
The analysis ID is `AYyYj`. 

Sorry, if I'm missing something obvious here.

**Comment by adelavega** [comment] 2020-05-29 01:34
hey, sorry that error is not more helpful. i looked at your model briefly and it looks good, so maybe its one of the fmriprep regressors. ill let you know if i find out more when i dig in.

**Comment by adelavega** [comment] 2020-05-29 01:45
try removing the fmriprep regressors and see if you get the same error. i know the 6 motion parameters should work, so you can leave those in and start there if you want.

**Comment by PeerHerholz** [comment] 2020-05-29 01:46
Check, on it!

**Comment by PeerHerholz** [comment] 2020-05-29 02:22
Reports generation takes a long time or doesn't work at all. Might be related to #755? Will try again and update tomorrow.

**Comment by rbroc** [comment] 2020-05-29 12:58
have been experiencing slow report generation too these last couple of days.

**Comment by adelavega** [comment] 2020-05-29 23:25
Looks like one of the issues is the `create_pes` function, which creates the timing of the predictors on demand from "stimulus" time, seems to be really slow, at least in this instance with AudioSet predictors

**Comment by adelavega** [comment] 2020-05-29 23:34
Unfortunately, I think I just need to optimize that function. For an audioset predictor, it took about a 1minute + to dump out a single predictor for a single run.... That's pretty slow.

That said, it created 18k timepoints, at around 10hz, which is probably why its so slow compared to the visual predictors which are at 1hz. 

One solution is to downsample everything going to the database to a coarser level, as 10hz is probably much more than we need for fmri, with slow TRs.

**Comment by PeerHerholz** [comment] 2020-05-30 01:49
Thx @adelavega for the updates and information! Re the error I received: I'm currently testing a step-wise increase of predictors. If I include the `AudioSet labels` and 6 `motion regressors` the reports are generated. Thus, the problem might be related to the `fmriprep` regressors as expected...maybe `framewise displacemen`. I'll update on report generation in #755.

**Comment by adelavega** [comment] 2020-05-31 23:32
Yes, I bet it's framewise displacement

**Comment by adelavega** [comment] 2020-06-02 23:06
@PeerHerholz this error is actually coming from `non_steady_state_outlier00*`. The issue is that this variable is actually `n/a` (i.e. there are no outliers!). 

The reason that the variable exists is that fmriprep probably detected an outlier in one of the runs, but not all. So it's `n/a` for some runs.

pybids then throws an error when I try to densify this variable, which is a bug. I think it should drop it instead of keep it n/a in dense format. 

I need to think a bit more about how to solve this, but in the meantime just leave those out of models!

**Comment by PeerHerholz** [comment] 2020-06-03 22:22
Thanks for checking and updating!

**Comment by adelavega** [comment] 2020-06-03 22:46
np. this should have been closed by #773

**Closed by adelavega** 2020-06-03 22:46 UTC
