### ISSUE TITLE
Implement Analysis Viewer

### ISSUE THREAD

**Issue by skept** [neuroscout/neuroscout#66] opened 2017-06-23 23:08 UTC
This will be a page to view everything about the analysis and its results without being able to edit anything. Locked analyses can only be opened in Analysis Viewer. Unlocked analyses can be opened in either the "Viewer" or "Builder". The Viewer could also be embedded in the "Review" tab of the Builder.

@tyarkoni @adelavega Am I thinking about this correctly?  The viewer will need to be spec'ed out before implementing.

**Comment by adelavega** [comment] 2017-07-27 18:02
My personal preference here is to have a "summary" pop up page when you click on an analysis, and a link to 'edit' which is only possible if you're the owner. There may be also a button "Fork and edit" which allows you to enter the editor because you created a new cloned version of the analysis.

**Comment by tyarkoni** [comment] 2017-07-27 22:00
Not sure there's a reason to have two separate interfaces, as opposed to an integrated Viewer/Builder that's only editable for someone with the right permissions (and when the analysis isn't locked). I agree that some kind of Summary tab makes sense to have, but we can probably make that the final tab in the menu, and then once an analysis is public (which implies that it's locked), the summary tab can be the default tab to load when a new analysis is navigated to. Clicking "Edit" would automatically switch the user to the first tab if they're currently on the summary (but probably leave them on whatever tab they're currently on if it's anything other than the summary).

**Comment by adelavega** [comment] 2017-07-27 22:13
That makes sense to me. If I remember correctly @skept was having some trouble locking the entire Builder, perhaps this was the issue.

**Comment by skept** [comment] 2017-07-28 22:32
@adelavega Yes, disabling fields with a flag is relatively easy to do for traditional form fields (e.g. text boxes, checkboxes, etc) but not as easy with others e.g. interactive tables, buttons that remove tags, etc. I'm already disabling edits when the analysis is locked, so when the user tries interacting with the forms, tables, etc nothing happens. I agree it would be nice if visually things don't look editable in "View" mode to begin with. In terms of implementation I think it'll be less work to have a separate Viewer interface which can mimic the same tab layout as the Builder interface and have an "Edit" button that would switch to the Builder interface with interactive forms, etc. This could look exactly as @tyarkoni describes with different default tabs based on view/edit mode. Or alternatively it the view mode could be a single page, without different tabs. Either way since it'll be a fairly static page it'll be super easy to play around with it until we get an information layout that we like.

**Comment by adelavega** [comment] 2018-08-23 19:01
Duplicate of #328

**Closed by adelavega** 2018-08-23 19:01 UTC
Labels: frontend
